### ISSUE TITLE
Duplicated row error not behaving as it should

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#686] opened 2021-11-02 01:32 UTC
UI is flagging duplicate species data, even if block and size data for the species are different:
![image](https://user-images.githubusercontent.com/50387396/139772225-f34db1b1-f2f8-4104-9946-47932d625cc4.png)

**Comment by bpasquer** [comment] 2021-11-02 04:28
In your example the 2 highlighted row do net refer to the same warning, the top row(1149) is a duplicate of row 1190, and the next row(1150) is a duplicate of 1191. 
Note that duplications are assessed by comparing site/date/depth/method/bock/species -Size and total are excluded from the check.
![Screenshot from 2021-11-02 15-24-06](https://user-images.githubusercontent.com/3733612/139786676-367148f5-e182-4be8-9c7c-a24f1e73ea50.png)

**Closed** 2021-11-02 23:35 UTC
