### ISSUE TITLE
Some Class/Order/Family level spp. observations not displaying in M2_inverts endpoint

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#726] opened 2021-12-16 00:49 UTC
Not sure how many others are affected by this, but some examples of observable items which are not appearing in the end points are:

Brachyura spp.
Paguroidea spp.
Paguridae spp.

Malocostraca should capture these, so not sure what's happening here?

**Comment by bpasquer** [comment] 2021-12-16 02:56
Paguridae spp. are actually present in the M2 inverts endpoint
I confirm the other 2 are missing. Looking at the observable item record for these two , it appears that they don't have family information unlike   "Paguridae spp.".

The SQL rule  for inverts says that it include everything in the class Malacostraca class except members of the family Palaemonidae.
`(oi.phylum = 'Arthropoda' and oi.class ='Malacostraca' and oi.family <>'Palaemonidae')` 

My suspicion is that because of how the exclusion is written, an observable item that does not have its family provided will be excluded too.
So the issue is most probably not limited to Brachyura spp.,Paguroidea spp..
It will be resolved in the first release of 2022

**Comment by LizziOh** [comment] 2021-12-16 03:17
It appears there are other parts of the code which include family in the logic (eg. molluscs) which will be affected.  In addition the cryptic fish endpoint code relies heavily on family references, and on inspection there are hundreds of observable item type 'Species' which have NULL family.  These are almost all superseded species.  Toni informs that Just set most taxonomic information to NULL for superseded species.  Code for method validations and endpoint inclusion previously applied to the currently accepted name - not the observable item name.  Is this a better solution for those example which are not higher level items but actually superseded species-level items? (rather than populating the observable item tables for hundreds of records) @bpasquer

**Comment by bpasquer** [comment] 2021-12-16 05:35
To clarify, the problematic bit in the code here  `(oi.phylum = 'Arthropoda' and oi.class ='Malacostraca' and oi.family <>'Palaemonidae')` is the <> which is the `NOT IN` operator which has a different behaviour to 'equal' when assessing the query. 
FYI there is a good explanation [here](http://www.sqlbadpractices.com/using-not-in-operator-with-null-values/)
I had similar issue with the  'NOT IN' in the past that I resolved by using "EXCEPT"  . 
So i may just be a matter of swapping the "not equal' with "except'.

**Comment by bpasquer** [comment] 2021-12-17 01:38
change implemented in https://github.com/aodn/nrmn-application/pull/728

**Comment by bpasquer** [comment] 2022-01-11 03:28
checking in the Prod NRMN database:
```sql 
select count(*) from nrmn.ep_m2_inverts where species_name ='Paguroidea spp.'
```
now returns
| count |
|---|
|4219|

**Closed** 2022-01-13 00:21 UTC
Labels: data
