### ISSUE TITLE
Missing cryptic fish records in endpoints

### ISSUE THREAD

**Issue by atcooper1** [aodn/nrmn-application#890] opened 2022-03-31 00:27 UTC
There are a number of records that appear to have not been migrated. These have been identified from Tas and SA records, but the issue is likely to be more widespread. See below spreadsheet for a list of examples

[Cryptic fish examples.xlsx](https://github.com/aodn/nrmn-application/files/8384959/Cryptic.fish.examples.xlsx)

**Comment by bpasquer** [comment] 2022-03-31 02:38
[check_missing_records.txt](https://github.com/aodn/nrmn-application/files/8385476/check_missing_records.txt)

I ran the query in the attached file against the ep_cryptic_fish endpoint and found all the  missing records listed in the sheet "Cryptic fish example". Was James looking at the latest version of the endpoint?
```sql
| site_name                | site_code | survey_date | survey_id | method | block | species_name              | size_class | total |
|--------------------------|-----------|-------------|-----------|--------|-------|---------------------------|------------|-------|
| Cape Coutts              | GSV151    | 2012-02-07  | 812324414 | 2      | 1     | Paraplesiops meleagris    | 0          | 2     |
| Cape Coutts              | GSV151    | 2012-02-07  | 812324414 | 2      | 1     | Pempheris multiradiata    | 0          | 1     |
| Carrickalinga North Site | GSV45     | 2017-03-07  | 912349693 | 2      | 2     | Helcogramma decurrens     | 2.5        | 13    |
| Greenly Island           | EYR33     | 2014-01-13  | 912343911 | 2      | 2     | Trinorfolkia clarkei      | 5          | 1     |
| Greenly Island           | EYR33     | 2014-01-13  | 912343909 | 2      | 1     | Vincentia conspersa       | 5          | 2     |
| Greenly Island           | EYR33     | 2014-01-13  | 912343909 | 2      | 2     | Vincentia conspersa       | 5          | 3     |
| Lady Bay                 | GSV110    | 2018-02-06  | 912351054 | 2      | 1     | Helcogramma decurrens     | 2.5        | 6     |
| Lady Bay                 | GSV110    | 2018-02-06  | 912351054 | 2      | 1     | Helcogramma decurrens     | 5          | 4     |
| Lasseters Reef           | GSV95     | 2014-02-05  | 912345024 | 2      | 1     | Aetapcus maculatus        | 0          | 1     |
| Lasseters Reef           | GSV95     | 2014-02-05  | 912345024 | 2      | 1     | Heteroclinus johnstoni    | 0          | 1     |
| Pearson Island Bay NW    | EYR24     | 2014-01-06  | 912343868 | 2      | 2     | Pempheris multiradiata    | 10         | 10    |
| Pearson Island North     | EYR27     | 2014-01-09  | 912343885 | 2      | 2     | Hypoplectrodes nigroruber | 15         | 1     |
| Pearson Island SE bay    | EYR28     | 2014-01-09  | 912343887 | 2      | 1     | Trinorfolkia clarkei      | 2.5        | 1     |
| Penneshaw Pub West       | GSV141    | 2019-03-06  | 912352466 | 2      | 1     | Helcogramma decurrens     | 0          | 1     |
| Yankalilla Mouth         | GSV113    | 2017-03-15  | 912350474 | 2      | 2     | Eocallionymus papilio     | 5          | 1     |
| Yankalilla Mouth         | GSV113    | 2018-02-06  | 912351047 | 2      | 1     | Bathygobius krefftii      | 7.5        | 1     |
| Yankalilla Mouth         | GSV113    | 2018-02-06  | 912351047 | 2      | 1     | Helcogramma decurrens     | 2.5        | 1     |
| Yankalilla Mouth         | GSV113    | 2018-02-06  | 912351050 | 2      | 1     | Helcogramma decurrens     | 2.5        | 1     |
| Yankalilla Mouth         | GSV113    | 2018-02-06  | 912351050 | 2      | 2     | Helcogramma decurrens     | 5          | 1     |
```

**Comment by bpasquer** [comment] 2022-03-31 02:53
Also, I've check the first 10 records in the list "others to check" and they're all present in the ep_cryptic_fish endpoint.

**Comment by atcooper1** [comment] 2022-03-31 22:48
Hi Bene, James has confirmed that he made a mistake and he can now see these 'missing' records in his endpoints. So it is just the missing "Unidentified fish" records that need resolving. I assume these are to do with missing family information? "Unidentified fish" has been superseded by "Actinopterygii spp." (ID 2657) but this can't have family information as it's a Class level record?

**Comment by bpasquer** [comment] 2022-04-01 02:51
They will appear even if they are Class level record, so that's probably not the problem
I can see some record of "Unidentified fish" in the ep_m2_cryptic fish endpoint.
 The surveyID missing unidentified fishes are not listed in the "cryptic fish examples.xlsx' files, can you  tell me what they are .

**Comment by atcooper1** [comment] 2022-04-12 05:13
For M2_cryptic: see below for examples of Actinopterygii spp. not appearing in endpoints from James Brook. This should be all of them, unless there are some from the 2016 data.
Second Valley Boat Shed,GSV26,R,2012-11-02,1,912345616,1,Unidentified fish,0,1
Rapid Head,GSV4,R,2018-02-13, 2, 912350918,2,Unidentified fish, 7.5,1
Olivers Reef, GSV107, 2013-03-04, 4, 912345634,1,Unidentified fish,10,1
Olivers Reef,GSV107, 2013-03-04, 4, 912345634,1,Unidentified fish, 2.5,1
Horny Point,EYR50, 2007-12-03, 1, 812302241,1,Unidentified fish, 3.5,1
Haycock Point,GSV2, 2007-03-01 ,1,812301061,1,Unidentified fish, 0,1
Dodd's Beach,GSV9, 2018-03-07 ,2,912350978,1,Unidentified fish, 2.5,1
Dodd's Beach,GSV9, 2007-02-25 ,4,812301254,1,Unidentified fish, 0,4
Dalby Island,EYR59, 2007-11-30,2,812302132,1,Unidentified fish, 0,1
Cape Elizabeth SZ Site2, SSG44 2013-02-25 ,2,812325172,1,Unidentified fish,0,1

**Comment by atcooper1** [comment] 2022-04-12 07:02
Hi Bene,
You too! I hope you enjoy the holidays with your family. Catch you in a few weeks.
Many thanks,

Toni


On 12 Apr 2022, at 3:47 pm, bpasquer ***@***.***> wrote:

﻿

Thanks Toni,
have a nice Easter break,

Bene



[https://esr-storage.s3.amazonaws.com/images/14051/161106/default/images/759665d311cab5c30a.png?override=1644984344<https://esr-storage.s3.amazonaws.com/images/14051/161106/default/images/759665d311cab5c30a.png?override=1644984344>]


Benedicte Pasquer
(she/her) • Project Officer

IMOS Australian Ocean Data Network

P: 6226 1927
•
imos.org.au<http://imos.org.au><http://imos.org.au<http://imos.org.au>>



A: University of Tasmania, Private Bag 110, Hobart, TAS, 7001 Australia






[https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e4810d.png<https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e4810d.png>]<https://www.instagram.com/imos_australia<https://www.instagram.com/imos_australia>>
[https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e547bb.png<https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e547bb.png>]<https://twitter.com/IMOS_AUS<https://twitter.com/IMOS_AUS>>
[https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e6cd2a.png<https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e6cd2a.png>]<https://www.facebook.com/IntegratedMarineObservingSystem/<https://www.facebook.com/IntegratedMarineObservingSystem/>>
[https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e80153.png<https://esr-storage.s3.amazonaws.com/images/14051/161106/icons/620d869e80153.png>]<https://www.linkedin.com/company/imos_aus<https://www.linkedin.com/company/imos_aus>>


IMOS acknowledges the Traditional Custodians and Elders of the land and sea on which we work and observe and recognise their
unique connection to land and sea. We pay our respects to Aboriginal and Torres Strait Islander peoples past, present and future.



________________________________

**Comment by bpasquer** [comment] 2022-04-26 04:11
It appears that all _"Unidentified fish"_ M2 observations are missing from the ep_m2_cryptic_fish endpoint.
This is because ep_m2_cryptic_fish specifically includes observable_item that are observable under M2 (as recorded in the in the table `methods_species` ), yet this observable_item is only listed as a M0 or M1 species probably because a specific observable_item for unidentified cryptic fish (_"Unidentified cryptic fish"_) exists in the DB

The issue can be resolved in two ways:
1 - update the `methods_species` table to list _"Unidentified fish"_  as a M2 species
2 - correct the observations so that they use _"Unidentified cryptic fish"_

Note that becasue ep_m2_cryptic combines conditions the actual method and the expected method ,  solution 1-should not result in -non cryptic- unidentified fish being reported in M2 (see the last line in the code snippet below):
```sql
CREATE MATERIALIZED VIEW nrmn.ep_m2_cryptic_fish AS
[...]
from nrmn.observation obs
	inner join nrmn.survey_method sm on sm.survey_method_id = obs.survey_method_id
	inner join nrmn.ep_survey_list sur on sur.survey_id = sm.survey_id
	inner join nrmn.ep_site_list sit on sit.site_code = sur.site_code
	inner join nrmn.diver_ref div ON div.diver_id = obs.diver_id
	inner join nrmn.ep_observable_items oi on oi.observable_item_id = obs.observable_item_id
	inner join nrmn.measure_ref meas ON meas.measure_id = obs.measure_id
	inner join nrmn.methods_species ms ON ms.observable_item_id = obs.observable_item_id
where sm.method_id = 2 and ms.method_id = 2 
[...]
```

Let me know what your preferred solution is

**Comment by bpasquer** [comment] 2022-04-26 04:18
Also while looking for the missing data I noticed that : 
> Horny Point,EYR50, 2007-12-03, 1, 812302241,1,Unidentified fish, 3.5,1

is actually recorded with a size_class of 35 instead of 3.5. 
Either it is not a cryptic fish or the size class is wrong and should be corrected

**Comment by bpasquer** [comment] 2022-05-10 01:42
It's been confirmed by James( email 2022-05-03) that "Unidentified fish" can be reserved for M1.

**Closed** 2022-05-12 23:54 UTC
