### ISSUE TITLE
No validation errors for duplicate rows

### ISSUE THREAD

**Issue by bpasquer** [aodn/nrmn-application#306] opened 2021-05-18 05:43 UTC
There is currently no check to identify duplicate rows (i.e. same date/depth/diver/site/block/method/species/Total/Invert/SizeClass)

Need to flag if a row is a perfect duplication as this could mean a diver has forgotten to switch blocks or has accidentally entered the same species twice.
It is possible to record the same species on the same block, but these records shouldn't directly precede one another (i.e. they are usually separated by other observations)

**Comment by utas-tajona** [comment] 2021-05-18 05:50
is it related to a validation describle in the [word document](https://universitytasmania-my.sharepoint.com/:w:/r/personal/cameron_moloney_utas_edu_au/_layouts/15/Doc.aspx?sourcedoc=%7B3C402E1B-6AC3-4C8B-A731-283FFF06B4F6%7D&file=NRMN%20-%20Specifications%20-%20Survey%20Data%20Validation%20Checks.docx&action=default&mobileredirect=true&cid=3bf697e9-f05a-4934-ac20-7a57ac89d16b) ?

**Comment by APaulic** [comment] 2021-06-30 04:34
Hi @atcooper1, I am looking at implementing this check but just wanted to confirm that the only requirements are that if two sequential rows have the same date, depth, diver, site, block, method, species, Total, Invert, SizeClass then to show a warning that there is a potential duplicate. The message would read "WARNING: Row 2 may be a duplicate of row 1."

**Comment by atcooper1** [comment] 2021-06-30 04:46
Hi @APaulic, the duplicate row validation should compare: date, depth, diver, site, block, method, species. total can be different and sizeclass/invert/unsized columns can be different. Currently the validation is only a warning, but the tool "stops" at the duplicated row as it is usually an indication that the diver has forgotten to switch methods. See example below:
![image](https://user-images.githubusercontent.com/50387396/123903345-e0452a00-d9b1-11eb-927e-63c0812c3aad.png)

**Comment by atcooper1** [comment] 2021-06-30 04:47
So a warning is fine as long as all duplications can be viewed in the order the data were entered so we can visually see it (in context with the rest of the survey) to see whether the duplication is a method error, or a true duplication error (or something else)

**Comment by APaulic** [comment] 2021-07-05 02:18
@atcooper1 I just wanted to clarify one thing. This check is only to capture a row that is a duplicate of the immediately preceding row. 

Do we also need to flag rows that are duplicates but not grouped together? This would capture the scenario where details are accidentally transcribed multiple times rather than not progressing block numbers.

**Comment by atcooper1** [comment] 2021-07-05 06:23
@APaulic if it's possible to display as a warning only (i.e. not blocking) then yes, that would be very, very helpful, thanks!

**Comment by LizziOh** [comment] 2021-09-01 06:19
validations now implemented for duplicate rows.  There are still issues with the display/grouping of the validations but these are addressed/discusses in issue #583  and #535

**Closed by LizziOh** 2021-09-01 06:19 UTC
Labels: new feature request, ready to test
